from sqlalchemy.orm.session import Session
from schemas import TestBase
from db.models import Db_Test

def insert_to_test_table(db: Session, request: TestBase):
    # This will effectively convert from TestBase(request parameter) to Db_Test
    # which will allow the db to understand the data. This passes the data from schemas.py
    # to a models.py (sort of!)
    data_to_insert = Db_Test(
        test_string_col = request.test_string_col
    )
    # Sends the data to the database
    db.add(data_to_insert)
    db.commit()
    # Makes sure the autogenerated id gets merged with the data to insert
    db.refresh(data_to_insert)